# Generated by Django 4.2.5 on 2024-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='website_url',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='brewery_type',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='rating',
        ),
        migrations.AlterField(
            model_name='brewery',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='id',
            field=models.UUIDField(default='5005417d-34ec-4108-97ef-68ed31bb3025', editable=False, primary_key=True, serialize=False),
        ),
    ]
