# Generated by Django 4.2.5 on 2024-06-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0002_rename_website_url_brewery_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='id',
            field=models.UUIDField(default='fca327cd-1ef6-4e24-be6d-6f4e7f84a53c', editable=False, primary_key=True, serialize=False),
        ),
    ]
